"use strict"

// Catálogo da aba Retro. A lista é formada exclusivamente pelos registros que
// a Hydra Library marca com status "Classics"; nenhum jogo é inventado a
// partir de uma busca Steam. O processo principal apenas lê/faz cache de JSONs
// públicos e o renderer recebe os URIs somente ao abrir o detalhe.
const fs = require("node:fs")
const path = require("node:path")
const os = require("node:os")
const crypto = require("node:crypto")
const { fetchRede } = require("./httpfetch")
const { getDataDir } = require("./runtime-paths")

const HYDRA_API = "https://api.hydralibrary.com/sources?status=Classics&limit=100"
const CACHE_FILE_NAME = "retro-catalog.json"
const CACHE_VERSION = 1
const CACHE_TTL_MS = 24 * 60 * 60 * 1000
const MAX_SOURCES = 100
const MAX_GAMES = 50000
const MAX_URIS = 16
const MAX_TITLE = 300
const MAX_DESCRIPTION = 2400
const MAX_LIMIT = 48
const MAX_QUERY = 120
const ID_RE = /^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$/

function safePublicUrl(value, maxLength = 2048) {
  if (typeof value !== "string" || !value.trim() || value.length > maxLength) return ""
  try {
    const u = new URL(value.trim())
    if (u.hash) return ""
    if (u.protocol !== "https:" || u.username || u.password || (u.port && u.port !== "443"))
      return ""
    const host = u.hostname.toLowerCase()
    if (
      host === "localhost" ||
      host === "127.0.0.1" ||
      host === "::1" ||
      host.startsWith("[") ||
      host.includes(":") ||
      /^(10|127)\./.test(host) ||
      /^192\.168\./.test(host) ||
      /^172\.(1[6-9]|2\d|3[0-1])\./.test(host)
    )
      return ""
    return u.toString()
  } catch {
    return ""
  }
}

function sourceId(value) {
  const id = String(value ?? "").trim()
  return ID_RE.test(id) || /^\d{1,12}$/.test(id) ? id : ""
}

function cleanText(value, max = MAX_DESCRIPTION) {
  let text = String(value || "")
    .replace(/<br\s*\/?>(?=\s*)/gi, "\n")
    .replace(/<[^>]*>/g, " ")
    .replace(/&nbsp;/gi, " ")
    .replace(/&amp;/gi, "&")
    .replace(/&quot;/gi, '"')
    .replace(/&#39;|&apos;/gi, "'")
    .replace(/&lt;/gi, "<")
    .replace(/&gt;/gi, ">")
    // Hydra feeds are not always generated by the same JSON writer. Decode
    // numeric entities as well, otherwise a title such as `Pokémon &#64;` can
    // never match the metadata provider's spelling.
    .replace(/&#(x[0-9a-f]+|\d+);/gi, (_match, code) => {
      const parsed = /^x/i.test(code) ? parseInt(code.slice(1), 16) : parseInt(code, 10)
      return Number.isFinite(parsed) && parsed >= 0 && parsed <= 0x10ffff
        ? String.fromCodePoint(parsed)
        : " "
    })
    .replace(/[\u0000-\u001f\u007f]/g, " ")
    .replace(/\s+/g, " ")
    .trim()
  return text.slice(0, max)
}

// Hydra's download title is often a ROM filename rather than the name a user
// would put in a library: `[PSX-PS3] Game [PKG] [USA / RUS]`, for example.
// Keep meaningful edition text in the title, but remove dump/region/format
// annotations so searches and cover providers receive a useful query.
const RETRO_FORMAT_TAG_RE =
  /^(?:7z|archive|bin(?:\s*\/\s*cue)?|cd|cso|cue|chd|disc|disk|dvd|e?boot|gdi|iso|nsp|pkg|rom|rvz|tap|torrent|wad|wbfs|xci)$/i
const RETRO_REGION_TAGS = new Set([
  "australia",
  "asia",
  "brazil",
  "canada",
  "europe",
  "eu",
  "eur",
  "france",
  "germany",
  "italy",
  "japan",
  "jp",
  "korea",
  "pal",
  "russia",
  "rus",
  "spain",
  "usa",
  "us",
  "u",
  "world",
  "ww",
])
const RETRO_LANGUAGE_TAGS = new Set([
  "ar",
  "br",
  "de",
  "en",
  "es",
  "fr",
  "it",
  "ja",
  "j",
  "ko",
  "pt",
  "ru",
  "sp",
  "zh",
  "eng",
  "jpn",
  "jap",
  "rus",
  "spa",
  "fra",
  "ger",
  "ita",
  "kor",
  "chn",
  "ntsc",
  "english",
  "french",
  "german",
  "italian",
  "japanese",
  "russian",
  "spanish",
])
const RETRO_PLATFORM_TAG_RE =
  /^(?:3do|amiga|arcade|atari(?:\s*2600|\s*5200|\s*7800)?|colecovision|dreamcast|game(?:boy|gear)|gba|gbc|genesis|megadrive|n(?:es|64|ds)|pc(?:\s+engine)?|pce(?:\s+cd)?(?:\s*[-/]\s*ps[1-5])?|psx?(?:\s*[-/]\s*(?:ps[1-5]|dvr))?|ps[1-5](?:\s*[-/]\s*ps[1-5])?|psp(?:\s*[-/]\s*ps[1-5])?|saturn|sega(?:\s*cd|\s*32x)?|snes|switch|wiiu?|xbox)$/i
const RETRO_SERIAL_TAG_RE =
  /^(?:[a-z]{2,8}[-_ ]?\d{2,}[a-z0-9\-/ %]*|\d{2,}[a-z][a-z0-9-]*|(?:rev|revision|ver|version|v|disc|disk|cd)\s*[a-z0-9._/-]+)$/i
const RETRO_FLAG_TAG_RE =
  /^(?:[!abfhp]|aftermarket|beta|convert|demo|digital|download|dlc|folder|full|hack|homebrew|mod|multi\d*|move|ntsc(?:-[a-z0-9]+)?|ode|pal|patch|pirate|proper|prototype|proto|region|repack|soft|translation|trainer|unl|unlicensed|virtual console)$/i
const RETRO_GROUP_TAG_RE = /^[\p{L}\p{N}][\p{L}\p{N}._'-]{1,31}$/u

function retroTagWords(value) {
  return String(value || "")
    .normalize("NFKC")
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .split(/[\s,;|/+&()\-]+/)
    .map((word) => word.trim())
    .filter(Boolean)
}

function isRetroMetadataToken(value) {
  const token = String(value || "")
    .trim()
    .toLowerCase()
  if (!token) return true
  if (RETRO_REGION_TAGS.has(token) || RETRO_LANGUAGE_TAGS.has(token)) return true
  if (RETRO_FORMAT_TAG_RE.test(token) || RETRO_PLATFORM_TAG_RE.test(token)) return true
  if (RETRO_FLAG_TAG_RE.test(token)) return true
  // Feed authors commonly combine language with a release qualifier:
  // `FullRUS`, `RUSSOUND`, `NTSC-J`, or `Multi10`.
  if (/^(?:full|multi)?(?:rus|eng|eur|jap|jpn|spa|fra|ger|ita|kor|chn)(?:sound)?$/i.test(token))
    return true
  if (/^(?:ntsc|pal)(?:[-_][a-z0-9]+)?$/i.test(token)) return true
  if (/^\d{1,3}%$/.test(token) || /^ird(?:\d+%?)?$/i.test(token)) return true
  if (/^(?:dvd|cd|disc)\d+$/i.test(token)) return true
  if (/^\d+$/.test(token)) return true
  return RETRO_SERIAL_TAG_RE.test(token)
}

function isRetroMetadataTag(value) {
  const tag = cleanText(value, 120)
    .replace(/^[-_.]+|[-_.]+$/g, "")
    .trim()
  if (!tag) return true
  if (RETRO_FORMAT_TAG_RE.test(tag) || RETRO_PLATFORM_TAG_RE.test(tag)) return true
  if (RETRO_SERIAL_TAG_RE.test(tag) || RETRO_FLAG_TAG_RE.test(tag)) return true
  // No-Intro and Redump use dates, revision labels, and region/language lists
  // in trailing groups. Only classify a group made entirely of known tokens;
  // this prevents meaningful `(Contra '93)` text from being discarded.
  if (/^(?:19|20)\d{2}(?:[-/.](?:0?\d|1[0-2]))?(?:[-/.](?:0?[1-9]|[12]\d|3[01]))?$/.test(tag))
    return true
  const words = retroTagWords(tag)
  if (!words.length) return true
  if (words.every(isRetroMetadataToken)) return true
  // Mixed release labels such as `ENG(RUS only sound)|NTSC` contain a few
  // descriptive words but remain unambiguously metadata when separators and
  // multiple region/language tokens are present.
  if (/[|/+,]/.test(tag) && words.filter((word) => isRetroMetadataToken(word)).length >= 2)
    return true
  if (words.some((word) => /^(?:rev|revision|ver|version|v)\d*$/i.test(word))) return true
  return false
}

function isRetroReleaseGroupTag(value) {
  const tag = cleanText(value, 120)
  if (!tag || isRetroMetadataTag(tag)) return false
  if (/^\d+\s+in\s+\d+$/i.test(tag)) return false
  // Uploader/release groups may contain spaces (`[ViT Company]`,
  // `[Golden Leon]`). They are metadata when adjacent to a known dump tag,
  // while edition names such as `[Director's Cut]` must remain visible.
  if (
    /\b(?:anniversary|collection|complete|cut|deluxe|director|edition|greatest|limited|remaster(?:ed)?|special|ultimate)\b/i.test(
      tag,
    )
  )
    return false
  if (
    /[\/|+,]/.test(tag) ||
    /[-–—]/.test(tag) ||
    /\b(?:company|convert|fan(?:s)?|mvo|retrogaming|rgr|studio|team|text|translation|transgen|version|voice|vhs)\b/i.test(
      tag,
    ) ||
    /(?:текст|озвуч|фанат|перевод)/i.test(tag)
  )
    return true
  const words = retroTagWords(tag)
  return (
    words.length > 0 &&
    words.length <= 4 &&
    /^[\p{L}\p{N}][\p{L}\p{N}._'’]*(?:\s+[\p{L}\p{N}][\p{L}\p{N}._'’]*)*$/u.test(tag)
  )
}

function stripRetroGroups(title) {
  let cleaned = title
  const squareGroups = [...cleaned.matchAll(/\[([^\]\n]*)\]/g)]
  // Release annotations can occur before a trailing patch/edition suffix, so
  // remove known square-bracket metadata throughout the filename, not only at
  // the very end. Unknown meaningful title groups remain untouched.
  if (squareGroups.some((match) => isRetroMetadataTag(match[1]))) {
    cleaned = cleaned.replace(/\s*\[([^\]\n]*)\]/g, (raw, value) => {
      if (isRetroMetadataTag(value) || isRetroReleaseGroupTag(value)) return ""
      return raw
    })
  }

  // Parenthetical metadata is intentionally handled only when it is trailing;
  // parentheses in proper titles and collection descriptions are common.
  let rest = cleaned
  const groups = []
  let match
  while ((match = /(?:\s*)(\[[^\]\n]*\]|\([^()\n]*\))\s*$/.exec(rest))) {
    const raw = match[1]
    groups.unshift({ raw, value: raw.slice(1, -1).trim() })
    rest = rest.slice(0, match.index).trim()
  }
  if (!groups.some((group) => isRetroMetadataTag(group.value))) return cleaned
  const kept = groups.filter(
    (group) =>
      !isRetroMetadataTag(group.value) &&
      !(group.raw.startsWith("[") && isRetroReleaseGroupTag(group.value)),
  )
  return `${rest}${kept.map((group) => ` ${group.raw}`).join("")}`.trim()
}

/**
 * Return a display/search title for a Hydra download.
 *
 * This function is deliberately conservative: it only strips known dump
 * metadata and leaves unknown multi-word groups alone. It is exported so the
 * parser contract can test real feed examples without requiring a network.
 */
function normalizeRetroTitle(value, max = MAX_TITLE) {
  const original = cleanText(value, max)
  if (!original) return ""
  let title = original
    .normalize("NFKC")
    .replace(/[\u2010-\u2015]/g, "-")
    .replace(/[_]+/g, " ")
    .replace(/\s+/g, " ")
    .replace(/\.(?:7z|7zip|bin|chd|cue|iso|nsp|pkg|rar|rom|rvz|wad|wbfs|xci)$/i, "")
    .trim()

  // Platform/source labels are usually prepended by Rutracker and should not
  // become part of the metadata-provider search string.
  while (true) {
    const leading = /^\s*(\[[^\]\n]*\]|\([^()\n]*\))\s*/.exec(title)
    if (!leading || !isRetroMetadataTag(leading[1].slice(1, -1))) break
    title = title.slice(leading[0].length).trim()
  }
  title = stripRetroGroups(title)

  // RuTracker often repeats an alias in parentheses instead of a real edition:
  // `.hack//Outbreak Part 3 (dot Hack - Part 3 - Outbreak)`.
  title = title.replace(/\s*\(([^()]*)\)/g, (whole, group, offset, full) => {
    const before = full
      .slice(0, offset)
      .trim()
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, " ")
    const words = String(group)
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, " ")
      .split(/\s+/)
      .filter((word) => word.length > 2)
    const overlap = words.filter((word) => before.includes(word)).length
    if (/^(?:dot\s+hack|biohazard|resident\s+evil)\b/i.test(String(group).trim())) return ""
    if (overlap >= 2) return ""
    return whole
  })

  // Translation patches are sometimes plain suffixes rather than groups:
  // `Title [JAP|NTSC] + Patch-ENG+`.
  title = title.replace(
    /\s*(?:[+]\s*)?(?:patch|translation)[-_\s]+(?:eng|rus|jap|jpn|eur|usa)(?:[+|/]?(?:eng|rus|jap|jpn|eur|usa))*[+]?\s*$/i,
    "",
  )

  // A few feeds use plain ` - ISO`/` - USA` suffixes instead of groups.
  title = title
    .replace(
      /\s*(?:[-–—|,:]\s*)?(?:7z|bin(?:\s*\/\s*cue)?|chd|cue|iso|nsp|pkg|rom|rvz|wad|wbfs|xci)\s*$/i,
      "",
    )
    .replace(/\s+/g, " ")
    .replace(/^[\s_-]+|[\s_-]+$/g, "")
    .trim()
  return title.slice(0, max)
}

function normalizeSource(value) {
  if (!value || typeof value !== "object") return null
  const statusValues = [value.status, value.tags, value.statuses, value.tag].flatMap((raw) =>
    Array.isArray(raw) ? raw : [raw],
  )
  const status = statusValues
    .filter((s) => typeof s === "string")
    .flatMap((s) => s.split(/[;,|]/))
    .map((s) => s.trim())
    .filter(Boolean)
  if (!status.some((s) => s.toLowerCase() === "classics")) return null
  const id = sourceId(value.id ?? value.sourceId)
  const url = safePublicUrl(value.url || value.link)
  const title = cleanText(value.title || value.name, 160)
  if (!id || !url || !title) return null
  return {
    id,
    title,
    description: cleanText(value.description, 500),
    url,
    gamesCount: Number.isSafeInteger(Number(value.gamesCount))
      ? Math.max(0, Number(value.gamesCount))
      : 0,
    status,
    registryUrl: `https://library.hydra.wiki/sources/${encodeURIComponent(id)}`,
  }
}

function normalizeUri(value) {
  if (typeof value !== "string") return ""
  const uri = value.trim()
  if (!uri || uri.length > 8192 || /[\u0000-\u001f\u007f]/.test(uri)) return ""
  if (/^magnet:/i.test(uri)) {
    try {
      const parsed = new URL(uri)
      const hasBtih = parsed.searchParams
        .getAll("xt")
        .some((xt) => /^urn:btih:[A-Za-z0-9]+$/i.test(xt))
      if (parsed.username || parsed.password || !hasBtih) return ""
      return `magnet:${uri.slice(uri.indexOf(":") + 1)}`
    } catch {
      return ""
    }
  }
  return safePublicUrl(uri, 8192)
}

/** Backwards-compatible name used by the catalog parser and callers. */
function cleanRetroTitle(value) {
  return normalizeRetroTitle(value, MAX_TITLE)
}

function normalizeGame(download, source, index) {
  if (!download || typeof download !== "object") return null
  const originalTitle = cleanText(download.title, MAX_TITLE)
  const title = cleanRetroTitle(originalTitle)
  const rawUris = Array.isArray(download.uris) ? download.uris : download.uri ? [download.uri] : []
  const uris = [...new Set(rawUris.map(normalizeUri).filter(Boolean))].slice(0, MAX_URIS)
  if (!title || !uris.length) return null
  return {
    id: `${source.id}:${index}`,
    title,
    ...(originalTitle && originalTitle !== title ? { originalTitle } : {}),
    sourceId: source.id,
    sourceTitle: source.title,
    platform: cleanText(download.platform, 60),
    description: cleanText(download.descriptionHtml || download.description, MAX_DESCRIPTION),
    ...(safePublicUrl(
      download.cover ||
        download.image ||
        download.thumbnail ||
        download.artwork ||
        download.header_image,
    )
      ? {
          cover: safePublicUrl(
            download.cover ||
              download.image ||
              download.thumbnail ||
              download.artwork ||
              download.header_image,
          ),
        }
      : {}),
    ...(safePublicUrl(download.capa || download.portrait || download.coverPortrait)
      ? { capa: safePublicUrl(download.capa || download.portrait || download.coverPortrait) }
      : {}),
    ...(safePublicUrl(download.fallbackCover || download.fallback_cover)
      ? { fallbackCover: safePublicUrl(download.fallbackCover || download.fallback_cover) }
      : {}),
    fileSize: cleanText(download.fileSize, 80),
    uploadDate: cleanText(download.uploadDate, 80),
    uris,
  }
}

function normalizePayload(data, source) {
  if (!data || typeof data !== "object" || Array.isArray(data)) return []
  if (typeof data.name !== "string" || !data.name.trim()) return []
  const downloads = data.downloads
  if (!Array.isArray(downloads)) return []
  const games = []
  for (let i = 0; i < downloads.length && games.length < MAX_GAMES; i++) {
    const game = normalizeGame(downloads[i], source, i)
    if (game) games.push(game)
  }
  return games
}

const MAX_JSON_BYTES = 64 * 1024 * 1024

async function readResponseJson(response) {
  const reader = response?.body?.getReader?.()
  if (!reader) return response.json()
  const chunks = []
  let total = 0
  try {
    while (true) {
      const part = await reader.read()
      if (part.done) break
      total += part.value?.byteLength || 0
      if (total > MAX_JSON_BYTES) {
        await reader.cancel().catch(() => {})
        throw new Error("JSON da fonte excede o limite")
      }
      chunks.push(part.value)
    }
  } finally {
    reader.releaseLock?.()
  }
  const bytes = Buffer.concat(chunks.map((chunk) => Buffer.from(chunk)))
  return JSON.parse(bytes.toString("utf8"))
}

async function readJson(fetchImpl, url, timeoutMs = 30000) {
  const controller = new AbortController()
  const timer = setTimeout(() => controller.abort(), timeoutMs)
  try {
    const response = await fetchImpl(url, {
      headers: { Accept: "application/json", "User-Agent": "Arcadia-Retro/1" },
      redirect: "error",
      signal: controller.signal,
    })
    if (!response?.ok) throw new Error(`HTTP ${response?.status || 0}`)
    const length = Number(response.headers?.get?.("content-length") || 0)
    if (length > MAX_JSON_BYTES) throw new Error("JSON da fonte excede o limite")
    return await readResponseJson(response)
  } finally {
    clearTimeout(timer)
  }
}

function pathHasSymlink(target, fsImpl = fs) {
  let current = path.resolve(target)
  const rootPath = path.parse(current).root
  while (current && current !== rootPath) {
    try {
      if (fsImpl.lstatSync(current).isSymbolicLink()) return true
    } catch (error) {
      if (error?.code !== "ENOENT") return true
    }
    const parent = path.dirname(current)
    if (parent === current) break
    current = parent
  }
  return false
}

function readCache(file, fsImpl = fs) {
  try {
    if (pathHasSymlink(file, fsImpl)) return null
    const value = JSON.parse(fsImpl.readFileSync(file, "utf8"))
    if (
      value?.version !== CACHE_VERSION ||
      !Array.isArray(value.games) ||
      !Array.isArray(value.sources)
    )
      return null
    return {
      ...value,
      games: value.games
        .filter((game) => game && typeof game === "object")
        .map((game) => ({
          ...game,
          title: cleanRetroTitle(game.title) || String(game.title || ""),
        })),
    }
  } catch {
    return null
  }
}

function writeCache(file, value, fsImpl = fs) {
  try {
    const directory = path.dirname(file)
    if (pathHasSymlink(directory, fsImpl)) return
    fsImpl.mkdirSync(directory, { recursive: true })
    if (pathHasSymlink(directory, fsImpl) || pathHasSymlink(file, fsImpl)) return
    const tmp = `${file}.tmp-${process.pid}`
    fsImpl.writeFileSync(tmp, JSON.stringify(value), { mode: 0o600 })
    fsImpl.renameSync(tmp, file)
  } catch {
    // O catálogo continua utilizável em memória mesmo sem disco gravável.
  }
}

function sourceCachePath(dataDir, url) {
  const id = crypto.createHash("sha256").update(String(url)).digest("hex").slice(0, 12)
  return path.join(dataDir, "sources", `${id}.json`)
}

function readLocalSourcePayload(dataDir, source, fsImpl = fs) {
  const file = sourceCachePath(dataDir, source.url)
  try {
    if (pathHasSymlink(file, fsImpl)) return null
    const stat = fsImpl.statSync(file)
    if (!stat.isFile() || stat.size > MAX_JSON_BYTES) return null
    return JSON.parse(fsImpl.readFileSync(file, "utf8"))
  } catch {
    return null
  }
}

function createRetroCatalog({
  dataDir = getDataDir(),
  fetchImpl = fetchRede,
  apiUrl = HYDRA_API,
  fsImpl = fs,
  now = () => Date.now(),
  sourcePayloads,
} = {}) {
  const cacheFile = path.join(path.resolve(String(dataDir || os.tmpdir())), CACHE_FILE_NAME)
  let memory = readCache(cacheFile, fsImpl)
  let inFlight = null

  const fetchSource = async (source) => {
    if (sourcePayloads && Object.prototype.hasOwnProperty.call(sourcePayloads, source.id)) {
      return normalizePayload(sourcePayloads[source.id], source)
    }
    try {
      const games = normalizePayload(await readJson(fetchImpl, source.url, 60000), source)
      if (games.length) return games
      const cached = readLocalSourcePayload(dataDir, source, fsImpl)
      return cached ? normalizePayload(cached, source) : games
    } catch (error) {
      const cached = readLocalSourcePayload(dataDir, source, fsImpl)
      if (cached) {
        const games = normalizePayload(cached, source)
        if (games.length) return games
      }
      throw error
    }
  }

  const refresh = async () => {
    const listing = await readJson(fetchImpl, apiUrl, 20000)
    const candidates = (Array.isArray(listing) ? listing : listing?.sources || [])
      .map(normalizeSource)
      .filter(Boolean)
      .slice(0, MAX_SOURCES)
    if (!candidates.length) throw new Error("Nenhuma fonte Classics encontrada")

    const results = await Promise.allSettled(
      candidates.map(async (source) => ({
        source,
        games: await fetchSource(source),
      })),
    )
    // Keep the metadata list even when one provider is temporarily offline;
    // the UI can still explain which tagged source was skipped.
    const sources = candidates
    const games = []
    for (const result of results) {
      if (result.status !== "fulfilled") continue
      games.push(...result.value.games)
      if (games.length >= MAX_GAMES) break
    }
    if (!games.length) {
      const error = new Error("As fontes Classics não retornaram jogos")
      error.sources = candidates
      throw error
    }
    games.sort((left, right) => {
      const title = left.title.toLowerCase().localeCompare(right.title.toLowerCase(), "en")
      return (
        title ||
        left.sourceId.localeCompare(right.sourceId, "en") ||
        left.id.localeCompare(right.id, "en")
      )
    })
    const catalog = {
      version: CACHE_VERSION,
      updatedAt: now(),
      sources,
      games: games.slice(0, MAX_GAMES),
    }
    memory = catalog
    writeCache(cacheFile, catalog, fsImpl)
    return catalog
  }

  const ensure = async (force = false) => {
    const fresh = memory && now() - Number(memory.updatedAt || 0) < CACHE_TTL_MS
    if (!force && fresh) return memory
    if (!force && memory) {
      if (!inFlight)
        inFlight = refresh()
          .catch(() => memory)
          .finally(() => {
            inFlight = null
          })
      return memory
    }
    if (!inFlight)
      inFlight = refresh().finally(() => {
        inFlight = null
      })
    return inFlight
  }

  async function list({ query = "", offset = 0, limit = 24, refresh: force = false } = {}) {
    const off = Math.max(0, Number.isSafeInteger(Number(offset)) ? Number(offset) : 0)
    const lim = Math.min(
      MAX_LIMIT,
      Math.max(1, Number.isSafeInteger(Number(limit)) ? Number(limit) : 24),
    )
    let catalog
    try {
      catalog = await ensure(Boolean(force))
    } catch (cause) {
      return {
        ok: false,
        games: [],
        sources: Array.isArray(cause?.sources) ? cause.sources : [],
        total: 0,
        offset: off,
        limit: lim,
        hasMore: false,
        error: String(cause?.message || cause),
      }
    }
    const q = String(query || "")
      .trim()
      .toLowerCase()
      .slice(0, MAX_QUERY)
    const all = q
      ? catalog.games.filter((game) =>
          [game.title, game.platform, game.sourceTitle, game.description]
            .filter(Boolean)
            .join(" ")
            .toLowerCase()
            .includes(q),
        )
      : catalog.games
    const games = all.slice(off, off + lim).map(({ uris, ...game }) => game)
    return {
      ok: true,
      games,
      sources: catalog.sources,
      total: all.length,
      offset: off,
      limit: lim,
      hasMore: off + games.length < all.length,
      updatedAt: catalog.updatedAt,
    }
  }

  async function getGame(id) {
    let catalog
    try {
      catalog = await ensure(false)
    } catch (cause) {
      return {
        ok: false,
        error: String(cause?.message || cause),
        sources: Array.isArray(cause?.sources) ? cause.sources : [],
      }
    }
    const key = String(id || "").trim()
    const game = catalog.games.find((candidate) => candidate.id === key)
    if (!game) return { ok: false, error: "jogo retro não encontrado", sources: catalog.sources }
    return { ok: true, game, sources: catalog.sources }
  }

  return { list, getGame, refresh, cacheFile }
}

const singleton = createRetroCatalog()
module.exports = {
  HYDRA_API,
  createRetroCatalog,
  list: singleton.list,
  getGame: singleton.getGame,
  refresh: singleton.refresh,
  normalizeSource,
  cleanRetroTitle,
  normalizeRetroTitle,
  normalizeGame,
  normalizePayload,
}
