CREATE TABLE IF NOT EXISTS profiles (
  id                 TEXT PRIMARY KEY,
  email              TEXT UNIQUE NOT NULL,
  password_hash      TEXT NOT NULL,
  username           TEXT UNIQUE NOT NULL CHECK (username ~ '^[a-z0-9_]{3,20}$'),
  avatar_url         TEXT,
  background_url     TEXT,
  banner_url         TEXT,
  steam_id           TEXT,
  display_name       TEXT,
  summary            TEXT,
  country            TEXT,
  city               TEXT,
  showcase           JSONB NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(showcase) = 'array'),
  profile_visibility TEXT NOT NULL DEFAULT 'public' CHECK (profile_visibility IN ('public','friends','private')),
  show_location      INTEGER NOT NULL DEFAULT 0,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_profiles_username ON profiles (username text_pattern_ops);

CREATE TABLE IF NOT EXISTS friendships (
  user_a       TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  user_b       TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  requester_id TEXT NOT NULL REFERENCES profiles(id),
  status       TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','accepted','blocked')),
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_a, user_b),
  CHECK (user_a < user_b)
);
CREATE INDEX IF NOT EXISTS idx_friendships_a ON friendships (user_a, status);
CREATE INDEX IF NOT EXISTS idx_friendships_b ON friendships (user_b, status);

CREATE TABLE IF NOT EXISTS user_achievements (
  user_id     TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  appid       TEXT NOT NULL,
  apiname     TEXT NOT NULL,
  unlocked_at BIGINT NOT NULL,
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  title       TEXT,
  icon        TEXT,
  percent     DOUBLE PRECISION,
  PRIMARY KEY (user_id, appid, apiname)
);
CREATE INDEX IF NOT EXISTS idx_achievements_since ON user_achievements (user_id, updated_at);

CREATE TABLE IF NOT EXISTS user_library (
  user_id    TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  appid      TEXT NOT NULL,
  title      TEXT NOT NULL DEFAULT '',
  platform   TEXT NOT NULL DEFAULT 'windows',
  added_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, appid)
);

CREATE TABLE IF NOT EXISTS user_playtime (
  user_id    TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  appid      TEXT NOT NULL,
  minutes    INTEGER NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, appid)
);

CREATE TABLE IF NOT EXISTS refresh_tokens (
  token      TEXT PRIMARY KEY,
  user_id    TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS login_attempts (
  username     TEXT PRIMARY KEY,
  attempts     INTEGER NOT NULL DEFAULT 1,
  window_start TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS reserved_usernames (
  username TEXT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS user_sources (
  user_id    TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  source_id  TEXT NOT NULL,
  url        TEXT NOT NULL,
  name       TEXT NOT NULL DEFAULT '',
  added_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  removed_at TIMESTAMPTZ,
  PRIMARY KEY (user_id, source_id)
);

CREATE TABLE IF NOT EXISTS blocks (
  blocker_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  blocked_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (blocker_id, blocked_id),
  CHECK (blocker_id <> blocked_id)
);

CREATE TABLE IF NOT EXISTS catalog_cache (
  key  TEXT PRIMARY KEY,
  data TEXT NOT NULL,
  at   BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS user_reviews (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  appid      TEXT NOT NULL,
  text       TEXT NOT NULL,
  positive   INTEGER NOT NULL DEFAULT 1,
  hours      DOUBLE PRECISION NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_user_reviews_appid ON user_reviews (appid);
