-- Arcadia migration 0003: comunidade (reviews, coleções e moderação).
-- Tudo nesta migration é aditivo e transacional. A tabela user_reviews existia
-- no baseline para a loja; ela recebe os campos de comunidade sem quebrar as
-- escritas legadas do endpoint /catalog/v1/reviews.

ALTER TABLE user_reviews
  ADD COLUMN IF NOT EXISTS title TEXT,
  ADD COLUMN IF NOT EXISTS rating SMALLINT NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'visible',
  ADD COLUMN IF NOT EXISTS moderation_reason TEXT,
  ADD COLUMN IF NOT EXISTS moderated_by TEXT REFERENCES profiles(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS reported_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

-- Registros antigos só tinham positive. Converte-os para a escala nova antes
-- de validar a coluna. A normalização mantém 1/5 para preservar o significado
-- positivo/negativo do endpoint legado.
UPDATE user_reviews
   SET rating = CASE WHEN positive = 0 THEN 1 ELSE 5 END
 WHERE rating IS NULL OR rating < 1 OR rating > 5;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conname = 'user_reviews_rating_check'
       AND conrelid = 'user_reviews'::regclass
  ) THEN
    ALTER TABLE user_reviews ADD CONSTRAINT user_reviews_rating_check
      CHECK (rating BETWEEN 1 AND 5);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conname = 'user_reviews_status_check'
       AND conrelid = 'user_reviews'::regclass
  ) THEN
    ALTER TABLE user_reviews ADD CONSTRAINT user_reviews_status_check
      CHECK (status IN ('visible', 'pending', 'hidden', 'rejected'));
  END IF;
END $$;

-- O produto garante uma avaliação por conta/jogo. Bases antigas podem ter
-- duplicatas criadas pela rota legada; conserva-se a mais recente antes do
-- índice único para a migration não falhar durante um upgrade.
DELETE FROM user_reviews newer
 USING user_reviews older
 WHERE newer.user_id = older.user_id
   AND newer.appid = older.appid
   AND (newer.created_at, newer.id) < (older.created_at, older.id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_user_reviews_user_appid
  ON user_reviews (user_id, appid);
CREATE INDEX IF NOT EXISTS idx_user_reviews_visible_appid
  ON user_reviews (appid, created_at DESC)
  WHERE status = 'visible';
CREATE INDEX IF NOT EXISTS idx_user_reviews_moderation
  ON user_reviews (status, reported_at DESC, created_at DESC);

CREATE TABLE IF NOT EXISTS collections (
  id          TEXT PRIMARY KEY,
  user_id     TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  title       TEXT NOT NULL,
  description TEXT,
  visibility  TEXT NOT NULL DEFAULT 'public'
              CHECK (visibility IN ('public', 'unlisted', 'private')),
  status      TEXT NOT NULL DEFAULT 'visible'
              CHECK (status IN ('visible', 'pending', 'hidden', 'rejected')),
  moderation_reason TEXT,
  moderated_by TEXT REFERENCES profiles(id) ON DELETE SET NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (char_length(title) BETWEEN 1 AND 120),
  CHECK (description IS NULL OR char_length(description) <= 2000)
);
CREATE INDEX IF NOT EXISTS idx_collections_public
  ON collections (created_at DESC, id)
  WHERE visibility = 'public' AND status = 'visible';
CREATE INDEX IF NOT EXISTS idx_collections_user_updated
  ON collections (user_id, updated_at DESC, id);

CREATE TABLE IF NOT EXISTS collection_items (
  collection_id TEXT NOT NULL REFERENCES collections(id) ON DELETE CASCADE,
  appid         TEXT NOT NULL CHECK (appid ~ '^[0-9]{1,10}$'),
  position      INTEGER NOT NULL CHECK (position >= 0 AND position < 500),
  title         TEXT,
  note          TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (collection_id, appid),
  UNIQUE (collection_id, position),
  CHECK (title IS NULL OR char_length(title) <= 200),
  CHECK (note IS NULL OR char_length(note) <= 500)
);
CREATE INDEX IF NOT EXISTS idx_collection_items_order
  ON collection_items (collection_id, position);

-- Relatos são polimórficos de propósito: uma futura versão pode receber
-- denúncias de comentários/atividades sem alterar a API de reports.
CREATE TABLE IF NOT EXISTS community_reports (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reporter_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  target_type TEXT NOT NULL CHECK (target_type IN ('review', 'collection')),
  target_id   TEXT NOT NULL,
  reason      TEXT NOT NULL CHECK (char_length(reason) BETWEEN 1 AND 80),
  details     TEXT,
  status      TEXT NOT NULL DEFAULT 'open'
              CHECK (status IN ('open', 'reviewed', 'dismissed', 'actioned')),
  moderator_id TEXT REFERENCES profiles(id) ON DELETE SET NULL,
  moderator_note TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (reporter_id, target_type, target_id),
  CHECK (details IS NULL OR char_length(details) <= 1000),
  CHECK (moderator_note IS NULL OR char_length(moderator_note) <= 1000)
);
CREATE INDEX IF NOT EXISTS idx_community_reports_queue
  ON community_reports (status, created_at ASC);
CREATE INDEX IF NOT EXISTS idx_community_reports_target
  ON community_reports (target_type, target_id, status);

-- A lista é deliberadamente vazia por padrão. Em produção o deploy pode
-- inserir usuários nesta tabela; COMMUNITY_MODERATOR_IDS continua disponível
-- para instalações simples e testes sem uma rotina de administração.
CREATE TABLE IF NOT EXISTS community_moderators (
  user_id    TEXT PRIMARY KEY REFERENCES profiles(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
