"use strict"

const test = require("node:test")
const assert = require("node:assert/strict")
const fs = require("node:fs")
const path = require("node:path")

const root = path.resolve(__dirname, "..")
const read = (...parts) => fs.readFileSync(path.join(root, ...parts), "utf8")

test("detalhe substitui o catálogo da loja em vez de renderizar depois dele", () => {
  const store = read("src", "components", "desktop", "StoreView.tsx")
  const early = store.lastIndexOf("if (pagina) {")
  const catalog = store.lastIndexOf("if (aba === \"retro\")")
  assert.ok(early >= 0 && early < catalog, "detalhe precisa retornar antes do catálogo")
  assert.doesNotMatch(store.slice(catalog), /\{pagina &&/)
})

test("detalhe da biblioteca substitui a grade em vez de sobrepor", () => {
  const library = read("src", "components", "desktop", "LibraryView.tsx")
  const page = library.indexOf("if (paginaLoja) {")
  const grid = library.indexOf("return (\n    <div className=\"flex h-full flex-col\">")
  assert.ok(page >= 0 && page < grid, "página Steam precisa retornar antes da grade")
  assert.match(library, /if \(pagina\) \{/)
  assert.doesNotMatch(library.slice(grid), /\{paginaLoja &&|\{pagina &&/)
})

test("detalhe Steam mantém o appid nas consultas e na bridge", () => {
  const detail = read("src", "components", "desktop", "StoreGamePage.tsx")
  const preload = read("electron", "preload.js")
  const main = read("electron", "main.js")
  const types = read("src", "global.d.ts")
  assert.match(detail, /<ReviewsPanel appid=\{jogo\.appid\}/)
  assert.match(detail, /<CommentsPanel appid=\{jogo\.appid\}/)
  assert.match(detail, /<CommunityPanel appid=\{jogo\.appid\}/)
  assert.match(preload, /getGameNews:.*news:game/)
  assert.match(main, /ipcMain\.handle\("news:game"/)
  assert.match(main, /ISteamNews\/GetNewsForApp\/v2/)
  assert.match(main, /resolveSteamNewsImage\(item\)/)
  assert.match(types, /getGameNews:/)
})

test("conquistas usam ícones grandes e hover isolado", () => {
  const detail = read("src", "components", "desktop", "StoreGamePage.tsx")
  const retroAchievements = read("src", "components", "desktop", "RetroAchievementsGamePanel.tsx")
  const screen = read("src", "components", "desktop", "AchievementsFullScreen.tsx")
  const css = read("src", "index.css")
  assert.match(detail, /<RetroAchievementsGamePanel title=\{jogo\.title\} systemId=\{retro\.systemId\}/)
  assert.match(retroAchievements, /allOpen && items\?\.length && <AchievementsFullScreen/)
  assert.match(retroAchievements, /items\.slice\(0, 6\)/)
  assert.match(screen, /overflow-y-auto/)
  assert.match(retroAchievements, /detail-achievements-all/)
  assert.match(retroAchievements, /detail-achievement-card[^\n]*h-\[210px\]/)
  assert.match(retroAchievements, /detail-achievement-icon[^\n]*aspect-square w-16/)
  assert.match(retroAchievements, /detail-achievement-card[^\n]*overflow-hidden/)
  assert.match(css, /\.detail-achievement-card:hover[^}]*transform: none/)
})

test("novidades extraem capa Steam e mantêm fallback visual", () => {
  const main = read("electron", "main.js")
  const steamNews = read("electron", "steam-news.js")
  assert.match(steamNews, /STEAM_CLAN_IMAGE/)
  assert.match(steamNews, /clan\.cloudflare\.steamstatic\.com\/images/)
  assert.match(steamNews, /og:image/)
  assert.match(main, /resolveSteamNewsImage\(item\)/)
})

test("trailer da loja abre um player real com fallback HLS", () => {
  const detail = read("src", "components", "desktop", "GameDetailPanels.tsx")
  const main = read("electron", "main.js")
  assert.match(detail, /import Hls from "hls\.js"/)
  assert.match(detail, /controls\s+autoPlay\s+muted\s+playsInline/)
  assert.match(detail, /const \[sel, setSel\]/)
  assert.match(detail, /setSel\(temMovie \? \{ tipo: "movie", idx: 0 \}/)
  assert.match(detail, /hls\.loadSource\(mov\.hls\)/)
  assert.match(detail, /mov\?\.mp4 \|\| mov\?\.webm/)
  assert.match(detail, /video|vidRef/)
  assert.match(detail, /preload="auto"/)
  assert.match(main, /Array\.isArray\(cached\?\.movies\)/)
})

test("ação principal de jogar fica somente na barra superior", () => {
  const detail = read("src", "components", "desktop", "StoreGamePage.tsx")
  assert.match(detail, /<PrimaryBtn onClick=\{onJogar\}/)
  assert.doesNotMatch(detail, /heroButton/)
})

test("detalhe Retro usa a composição Hydra compartilhada", () => {
  const detail = read("src", "components", "desktop", "StoreGamePage.tsx")
  const retro = read("src", "components", "desktop", "RetroStoreView.tsx")
  const retroAchievements = read("src", "components", "desktop", "RetroAchievementsGamePanel.tsx")
  const retroBranch = detail.indexOf("{isRetro ? (")
  const achievements = detail.indexOf("<RetroAchievementsGamePanel", retroBranch)
  const description = detail.indexOf("<GameDescription")

  assert.ok(retroBranch >= 0 && description >= 0 && achievements > retroBranch)
  assert.match(detail, /isRetro \? retroScreenshots : info\?\.screenshots/)
  assert.match(detail, /isRetro \? undefined : info\?\.about/)
  assert.match(retro, /import \{ StoreGamePage, type RetroStoreDetail \}/)
  assert.match(retro, /<StoreGamePage[\s\S]*retro=\{/)
  assert.match(retroAchievements, /compact = false/)
  assert.match(retroAchievements, /detail-achievement-grid grid max-h-\[210px\].*overflow-y-auto/)
  assert.match(retroAchievements, /allOpen && items\?\.length && <AchievementsFullScreen/)
  assert.match(retroAchievements, /items\.slice\(0, 6\)/)
  assert.match(retroAchievements, /detail-achievements-all/)
  assert.match(retroAchievements, /h-\[286px\] overflow-hidden/)
})

test("catálogo da Loja usa linhas compactas e Retro usa paginação", () => {
  const store = read("src", "components", "desktop", "StoreView.tsx")
  const retro = read("src", "components", "desktop", "RetroStoreView.tsx")
  const shared = read("src", "components", "desktop", "storeShared.tsx")
  const css = read("src", "index.css")
  assert.match(store, /onScroll=\{carregarMaisCatalogo\}/)
  assert.doesNotMatch(retro, /new IntersectionObserver/)
  assert.match(retro, /<RetroCard/)
  assert.match(retro, /retro_pagination/)
  assert.match(retro, /retro_page_of/)
  assert.match(store, /<LinhaLoja/)
  assert.doesNotMatch(store, /<CartaoLoja/)
  assert.match(shared, /export function LinhaLoja/)
  assert.match(shared, /store-catalog-row group flex/)
  assert.match(shared, /jogo\.fontes/)
  assert.match(css, /\.store-catalog-row:hover/)
  assert.match(css, /\.store-catalog-art/)
})
