"use strict"

const test = require("node:test")
const assert = require("node:assert/strict")
const fs = require("node:fs")
const path = require("node:path")

const root = path.resolve(__dirname, "..")
const read = (...parts) => fs.readFileSync(path.join(root, ...parts), "utf8")

test("detalhe substitui o catálogo da loja em vez de renderizar depois dele", () => {
  const store = read("src", "components", "desktop", "StoreView.tsx")
  const early = store.lastIndexOf("if (pagina) {")
  const catalog = store.lastIndexOf("if (aba === \"retro\")")
  assert.ok(early >= 0 && early < catalog, "detalhe precisa retornar antes do catálogo")
  assert.doesNotMatch(store.slice(catalog), /\{pagina &&/)
})

test("detalhe da biblioteca substitui a grade em vez de sobrepor", () => {
  const library = read("src", "components", "desktop", "LibraryView.tsx")
  const page = library.indexOf("if (paginaLoja) {")
  const grid = library.indexOf("return (\n    <div className=\"flex h-full flex-col\">")
  assert.ok(page >= 0 && page < grid, "página Steam precisa retornar antes da grade")
  assert.match(library, /if \(pagina\) \{/)
  assert.doesNotMatch(library.slice(grid), /\{paginaLoja &&|\{pagina &&/)
})

test("detalhe usa notícias Steam específicas do appid", () => {
  const detail = read("src", "components", "desktop", "ArcadiaStoreGameDetail.tsx")
  const preload = read("electron", "preload.js")
  const main = read("electron", "main.js")
  const types = read("src", "global.d.ts")
  assert.match(detail, /getGameNews\(appid\)/)
  assert.doesNotMatch(detail, /getNews\(\)/)
  assert.match(preload, /getGameNews:.*news:game/)
  assert.match(main, /ipcMain\.handle\("news:game"/)
  assert.match(main, /ISteamNews\/GetNewsForApp\/v2/)
  assert.match(main, /resolveSteamNewsImage\(item\)/)
  assert.match(types, /getGameNews:/)
})

test("conquistas usam ícones grandes e hover isolado", () => {
  const detail = read("src", "components", "desktop", "ArcadiaStoreGameDetail.tsx")
  const screen = read("src", "components", "desktop", "AchievementsFullScreen.tsx")
  const css = read("src", "index.css")
  assert.match(detail, /allOpen && items\?\.length && <AchievementsFullScreen/)
  assert.match(detail, /items\.slice\(0, 6\)/)
  assert.match(screen, /overflow-y-auto/)
  assert.match(detail, /detail-achievements-all/)
  assert.match(detail, /DetailPanel className="h-\[286px\] overflow-hidden" title="Conquistas"/)
  assert.match(detail, /detail-achievement-card[^\n]*h-\[210px\]/)
  assert.match(detail, /detail-achievement-icon[^\n]*aspect-square w-16/)
  assert.match(detail, /detail-achievement-card[^\n]*overflow-hidden/)
  assert.match(css, /\.detail-achievement-card:hover[^}]*transform: none/)
  assert.match(detail, /detail-news-item/)
  assert.match(detail, /DetailPanel className="h-\[286px\] overflow-hidden" title="Novidades"/)
  assert.match(css, /\.detail-news-summary \{ -webkit-line-clamp: 3; \}/)
})

test("novidades extraem capa Steam e mantêm fallback visual", () => {
  const detail = read("src", "components", "desktop", "ArcadiaStoreGameDetail.tsx")
  const main = read("electron", "main.js")
  const steamNews = read("electron", "steam-news.js")
  assert.match(steamNews, /STEAM_CLAN_IMAGE/)
  assert.match(steamNews, /clan\.cloudflare\.steamstatic\.com\/images/)
  assert.match(steamNews, /og:image/)
  assert.match(detail, /<NewsPanel items=\{news\} fallbackImage=\{header\}/)
})

test("trailer da loja abre um player real com fallback HLS", () => {
  const detail = read("src", "components", "desktop", "ArcadiaStoreGameDetail.tsx")
  const main = read("electron", "main.js")
  assert.match(detail, /import Hls from "hls\.js"/)
  assert.match(detail, /<video ref=\{videoRef\}[^>]*controls autoPlay muted playsInline/)
  assert.match(detail, /const \[selectedMovie, setSelectedMovie\] = useState<Movie \| null>\(null\)/)
  assert.match(detail, /setSelectedMovie\(null\)/)
  assert.match(detail, /thumbs\[0\]\?\.movie && <button onClick=\{\(\) => selectMedia\(thumbs\[0\]\)\}/)
  assert.doesNotMatch(detail, /const firstMovie = info\?\.movies\?\.find/)
  assert.doesNotMatch(detail, /setSelectedMovie\(firstMovie \|\| null\)/)
  assert.match(detail, /video\.play\(\)\.catch/)
  assert.match(detail, /preload="auto"/)
  assert.match(detail, /hls\.loadSource\(selectedMovie\.hls\)/)
  assert.match(detail, /item\.mp4 \|\| item\.webm \|\| item\.hls/)
  assert.match(main, /Array\.isArray\(cached\?\.movies\)/)
  assert.doesNotMatch(detail, /movie: true/)
})

test("ação principal de jogar fica somente na barra superior", () => {
  const detail = read("src", "components", "desktop", "ArcadiaStoreGameDetail.tsx")
  assert.match(detail, /\{primary && <ActionButton action=\{primary\} \/>\}/)
  assert.doesNotMatch(detail, /<ActionButton action=\{primary\} heroButton \/>/)
})

test("detalhe Retro preserva a mesma composição visual do detalhe normal", () => {
  const detail = read("src", "components", "desktop", "ArcadiaStoreGameDetail.tsx")
  const retroAchievements = read("src", "components", "desktop", "RetroAchievementsGamePanel.tsx")
  const retroBranch = detail.indexOf("{retro ? (")
  const achievements = detail.indexOf("<RetroAchievementsGamePanel", retroBranch)
  const description = detail.indexOf('title="Descrição"', retroBranch)

  assert.ok(retroBranch >= 0 && achievements > retroBranch && description > achievements)
  assert.match(detail, /isRetro \? \(\s*<img[^>]*object-contain/)
  assert.doesNotMatch(detail, /!retro && <DetailPanel title="Amigos que jogam"/)
  assert.match(retroAchievements, /compact = false/)
  assert.match(retroAchievements, /detail-achievement-grid grid max-h-\[210px\].*overflow-y-auto/)
  assert.match(retroAchievements, /allOpen && items\?\.length && <AchievementsFullScreen/)
  assert.match(retroAchievements, /items\.slice\(0, 6\)/)
  assert.match(retroAchievements, /detail-achievements-all/)
  assert.match(retroAchievements, /h-\[286px\] overflow-hidden/)
})
